name: riverpod_zap
description: Support for `riverpod` in zap components.
version: 0.1.2
homepage: https://simonbinder.eu/zap/

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  riverpod: ^2.6.1
  zap: ^0.3.0
  # Note: Even when the root build is happening from another package, zap_dev
  # should be applied to this one.
  zap_dev: ^0.3.0

dev_dependencies:
  build_runner: ^2.5.1
  build_test: ^3.0.0
  build_web_compilers: ^4.1.5
  lints: ^6.0.0
  test: ^1.26.2
