name: tools
publish_to: none

environment:
  sdk: ^3.8.0

# dependencies:
#   simons_pub_uploader:
#     hosted: https://simonbinder.eu
#     version: ^1.1.0

workspace:
  # - docs
  - riverpod_zap
  - riverpod_zap/example
  - zap
  - zap_dev