name: zap_workspace
publish_to: none

environment:
  sdk: ^3.8.2

dependencies:
  simons_pub_uploader:
    hosted: https://pub-simonbinder-eu.fsn1.your-objectstorage.com
    version: ^1.2.1

workspace:
  - docs
  - riverpod_zap
  - riverpod_zap/example
  - zap
  - zap_dev
