builders:
  index_samples:
    build_to: cache
    import: 'tool/index_examples.dart'
    builder_factories: ["IndexExamples.new"]
    build_extensions: {'.dart': ['json']}
  extract_versions:
    build_to: cache
    import: 'tool/write_versions.dart'
    builder_factories: ["WriteVersions.new"]
    build_extensions: {'pubspec.yaml': ['lib/src/getting_started/versions.dart']}

targets:
  $default:
    sources:
      - "lib/**"
      - "pages/**"
      - "templates/**"
      - "web/**"
      - "tool/**"
      - "$package$"
      - "pubspec.yaml"
      - "theme.yaml"
      - "website.yaml"
    builders:
      ":index_samples":
        enabled: true
      ":extract_versions":
        enabled: true

global_options:
  build_web_compilers:ddc:
    options:
      environment:
        MAPBOX_TOKEN: mapbox_token
  build_web_compilers|entrypoint:
    options:
      compilers:
        # todo: Set right token from environment, but how?
        dart2js:
          args:
            - "-DMAPBOX_TOKEN=mapbox_token"
        dart2wasm:
          args:
            - "-DMAPBOX_TOKEN=mapbox_token"

additional_public_assets:
  - "pages/**"
