builders:
  index_samples:
    build_to: cache
    import: 'tool/index_examples.dart'
    builder_factories: ["IndexExamples.new"]
    build_extensions: {'.dart': ['json']}
  extract_versions:
    build_to: cache
    import: 'tool/write_versions.dart'
    builder_factories: ["WriteVersions.new"]
    build_extensions: {'pubspec.yaml': ['lib/src/getting_started/versions.dart']}

targets:
  $default:
    sources:
      - "lib/**"
      - "pages/**"
      - "templates/**"
      - "web/**"
      - "tool/**"
      - "$package$"
      - "pubspec.yaml"
      - "theme.yaml"
      - "website.yaml"
    builders:
      ":index_samples":
        enabled: true
      ":extract_versions":
        enabled: true

global_options:
  build_web_compilers|entrypoint:
    options:
        dart2js_args:
          # todo: Set right token from environment, but how?
          - "-DMAPBOX_TOKEN=pk.eyJ1IjoiYmluZGVyc2ltIiwiYSI6ImNsMGh5enpzaTAwN20zY240d25xcWV0NmwifQ.1lxhWKm1hE2SslHhD3dDNg"

additional_public_assets:
  - "pages/**"
