name: example
description: Demo of using riverpod and zap for a simple todo app.
publish_to: none

environment:
  sdk: ^3.8.2

resolution: workspace

dependencies:
  riverpod: ^2.6.1
  uuid: ^4.5.1
  picocss:
    hosted: https://pub-simonbinder-eu.fsn1.your-objectstorage.com
    version: ^2.0.6+1
  riverpod_zap:
    hosted: https://pub-simonbinder-eu.fsn1.your-objectstorage.com
    version: ^0.2.0
  web: ^1.1.1
  zap: ^0.3.0

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.0
  lints: ^6.0.0
  sass_builder: ^2.2.2-dev.0
  zap_dev: ^0.3.0
