name: example
description: Demo of using riverpod and zap for a simple todo app.
publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  riverpod: ^2.6.1
  uuid: ^4.5.1
  picocss:
    hosted: https://simonbinder.eu
    version: ^1.5.10
  riverpod_zap: ^0.2.0
  web: ^1.1.1
  zap: ^0.3.0

dev_dependencies:
  build_runner: ^2.5.2
  build_web_compilers: ^4.1.5
  lints: ^6.0.0
  sass_builder: ^2.2.1
  zap_dev: ^0.3.0
